import type { CookieSite } from "~/stores/WebPrivacyStore";
export const websites: CookieSite[] = [
  {
    id: "site-1",
    name: "DailyNews NG",
    domain: "dailynews.ng",
    thirdParties: ["ads.example.net", "trk.analytics.io"],
    reputation: 45,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-2",
    name: "ShopNaija",
    domain: "shopnaija.com",
    thirdParties: ["payments.partner", "ads.example.net", "recommend.shoplib"],
    reputation: 70,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-3",
    name: "LocalForum",
    domain: "localforum.ng",
    thirdParties: ["cdn.thirdparty", "analytics.party"],
    reputation: 30,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-4",
    name: "TechPulse",
    domain: "techpulse.io",
    thirdParties: ["ads.network", "tracker.io"],
    reputation: 60,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-5",
    name: "EduPortal",
    domain: "eduportal.ng",
    thirdParties: ["analytics.edu", "cdn.partner"],
    reputation: 20,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-6",
    name: "FoodiesHub",
    domain: "foodieshub.com",
    thirdParties: ["ads.food", "tracker.food", "recommend.recipes"],
    reputation: 50,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-7",
    name: "TravelNaija",
    domain: "travelnaija.ng",
    thirdParties: ["ads.travel", "analytics.travel"],
    reputation: 65,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-8",
    name: "ShopEasy",
    domain: "shopeasy.com",
    thirdParties: ["ads.shop", "tracking.io", "recommend.shop"],
    reputation: 75,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-9",
    name: "NaijaSports",
    domain: "naijasports.ng",
    thirdParties: ["ads.sports", "analytics.sports"],
    reputation: 40,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-10",
    name: "HealthLine",
    domain: "healthline.ng",
    thirdParties: ["analytics.health", "ads.health"],
    reputation: 55,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-11",
    name: "MovieBuzz",
    domain: "moviebuzz.com",
    thirdParties: ["ads.movies", "tracker.movies", "recommend.movies"],
    reputation: 35,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-12",
    name: "GameArena",
    domain: "gamearena.ng",
    thirdParties: ["ads.games", "analytics.games"],
    reputation: 50,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-13",
    name: "FashionFiesta",
    domain: "fashionfiesta.com",
    thirdParties: ["ads.fashion", "recommend.fashion"],
    reputation: 60,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-14",
    name: "JobPortal",
    domain: "jobportal.ng",
    thirdParties: ["ads.jobs", "analytics.jobs"],
    reputation: 45,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-15",
    name: "CryptoWatch",
    domain: "cryptowatch.io",
    thirdParties: ["ads.crypto", "tracker.crypto"],
    reputation: 70,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-16",
    name: "MusicStream",
    domain: "musicstream.com",
    thirdParties: ["ads.music", "analytics.music"],
    reputation: 55,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-17",
    name: "BlogNaija",
    domain: "blognaija.ng",
    thirdParties: ["ads.blog", "tracker.blog"],
    reputation: 35,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-18",
    name: "PhotoGallery",
    domain: "photogallery.com",
    thirdParties: ["cdn.photos", "analytics.photos"],
    reputation: 50,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-19",
    name: "NewsHub",
    domain: "newshub.ng",
    thirdParties: ["ads.news", "tracker.news"],
    reputation: 40,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-20",
    name: "EduConnect",
    domain: "educonnect.ng",
    thirdParties: ["analytics.edu", "cdn.partner"],
    reputation: 25,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-21",
    name: "FoodCorner",
    domain: "foodcorner.com",
    thirdParties: ["ads.food", "tracker.food", "recommend.food"],
    reputation: 55,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-22",
    name: "TravelWorld",
    domain: "travelworld.io",
    thirdParties: ["ads.travel", "analytics.travel", "cdn.travel"],
    reputation: 65,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-23",
    name: "ShopQuick",
    domain: "shopquick.com",
    thirdParties: ["ads.shop", "tracker.shop"],
    reputation: 70,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-24",
    name: "SportsArena",
    domain: "sportsarena.ng",
    thirdParties: ["ads.sports", "analytics.sports"],
    reputation: 45,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-25",
    name: "HealthCorner",
    domain: "healthcorner.ng",
    thirdParties: ["analytics.health", "ads.health"],
    reputation: 50,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-26",
    name: "MovieTime",
    domain: "movietime.com",
    thirdParties: ["ads.movies", "tracker.movies"],
    reputation: 35,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-27",
    name: "GameZone",
    domain: "gamezone.ng",
    thirdParties: ["ads.games", "analytics.games"],
    reputation: 60,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-28",
    name: "FashionHub",
    domain: "fashionhub.com",
    thirdParties: ["ads.fashion", "recommend.fashion"],
    reputation: 55,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-29",
    name: "JobFinder",
    domain: "jobfinder.ng",
    thirdParties: ["ads.jobs", "analytics.jobs"],
    reputation: 40,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-30",
    name: "CryptoNews",
    domain: "cryptonews.io",
    thirdParties: ["ads.crypto", "tracker.crypto"],
    reputation: 70,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-31",
    name: "StreamIt",
    domain: "streamit.com",
    thirdParties: ["ads.media", "analytics.media"],
    reputation: 55,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-32",
    name: "BlogHub",
    domain: "bloghub.ng",
    thirdParties: ["ads.blog", "tracker.blog"],
    reputation: 35,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-33",
    name: "PhotoSpot",
    domain: "photospot.com",
    thirdParties: ["cdn.photos", "analytics.photos"],
    reputation: 50,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-34",
    name: "NewsDaily",
    domain: "newsdaily.ng",
    thirdParties: ["ads.news", "tracker.news"],
    reputation: 45,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-35",
    name: "EduLearn",
    domain: "edulearn.ng",
    thirdParties: ["analytics.edu", "cdn.partner"],
    reputation: 25,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-36",
    name: "FoodSpot",
    domain: "foodspot.com",
    thirdParties: ["ads.food", "tracker.food"],
    reputation: 55,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-37",
    name: "TravelGo",
    domain: "travelgo.io",
    thirdParties: ["ads.travel", "analytics.travel"],
    reputation: 65,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-38",
    name: "ShopMart",
    domain: "shopmart.com",
    thirdParties: ["ads.shop", "tracker.shop"],
    reputation: 70,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-39",
    name: "SportsDaily",
    domain: "sportsdaily.ng",
    thirdParties: ["ads.sports", "analytics.sports"],
    reputation: 45,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "disabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-40",
    name: "HealthToday",
    domain: "healthtoday.ng",
    thirdParties: ["analytics.health", "ads.health"],
    reputation: 50,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-41",
    name: "MovieStream",
    domain: "moviestream.com",
    thirdParties: ["ads.movies", "tracker.movies"],
    reputation: 35,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
  {
    id: "site-42",
    name: "GameCentral",
    domain: "gamecentral.ng",
    thirdParties: ["ads.games", "analytics.games"],
    reputation: 60,
    categories: {
      essential: "enabled",
      analytics: "enabled",
      marketing: "enabled",
      third_party: "disabled",
    },
  },
  {
    id: "site-43",
    name: "FashionCorner",
    domain: "fashioncorner.com",
    thirdParties: ["ads.fashion", "recommend.fashion"],
    reputation: 55,
    categories: {
      essential: "enabled",
      analytics: "disabled",
      marketing: "enabled",
      third_party: "enabled",
    },
  },
];
